---
title: "git_00"
author: "Matthew Ramirez"
date: "Year 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
  
“Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

I have been one acquainted with the night.  
I have walked out in rain—and back in rain.  
I have outwalked the furthest city light.  

I have looked down the saddest city lane.  
I have passed by the watchman on his beat  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Under the billowing heat of the white  
tarpaulin church tent, my mother lowered  
her worshipping hands and leaned into me.  
  
“You’re running away from your calling.  
Your gift for words is meant for church  
and not for that skeptical head of yours.”  
  
The night air was thick with the scent  
of Charlie perfume, earth, and sweat,  
with a chorus of handheld fans fluttering.  
  
My doubts doubled due to the shouting  
pastor fleecing his flock for small bills  
to shop for planes and limousines.  
  
“Even broken men,” she said, “could channel   
God’s will. Despite their flaws, in the midst  
of their damage, a light can shine divine.”  
  
But all my life I’d remain a questioning man,  
choosing debate over faith, sparring   
with mystery, claiming logic over belief.  
  